# Generated by Django 3.2.6 on 2021-08-28 12:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('about', models.TextField(blank=True, max_length=100, null=True, verbose_name='About')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('about', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_main', models.ImageField(blank=True, help_text='485x600', null=True, upload_to='User_Pictures/', verbose_name=' picture for portfolio')),
                ('picture_blog', models.ImageField(blank=True, help_text='120x120', null=True, upload_to='User_Pictures/', verbose_name='picture for blog')),
                ('summery', ckeditor.fields.RichTextField()),
                ('about', ckeditor.fields.RichTextField()),
                ('end_about_me', ckeditor.fields.RichTextField()),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone')),
                ('Location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Location')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='Github')),
                ('skype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skype')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('total_project', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total project')),
                ('total_volunteers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total volunteers')),
                ('total_donation', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total donation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Informations',
            },
        ),
    ]
