# Generated by Django 3.2.5 on 2021-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summery',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Summery'),
        ),
    ]
