# Generated by Django 3.2.6 on 2021-08-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Account', '0001_initial'),
        ('Paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papers',
            new_name='My_Papers',
        ),
    ]
